### ISSUE TITLE
ModMaker DLC extract warning & procedure

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#140]
A couple things with this new feature:
1. Is there a way to prevent this warning from triggering if DLC are already extracted? It's going to confuse users. The warning comes across as "you better click on this or your game will be broken!", and yet, I was confused as to what to do since my DLC was already extracted.
2. On my system the warning was triggered upon TOCing (according to lower left progress bar). This seems like the wrong time. If we're going to give users the chance to deny the extraction, then it makes  makes much more sense for the warning to pop up after clicking on Run All/Run Selected. Before any action is taken.
3. I installed a MOD file to From Ashes. That was the only DLC modified. Yet, the Debug window still said all DLC were extracted and TOC'd -- and they were indeed all TOC'd. This leads me to believe that MM would have extracted all my DLC, if they had not already been. My impression was that this wasn't supposed to happen and only affected DLC should have been extracted/TOC'd.

**Comment by KFreon** [comment]
1. Fixed.
2. Fixed, with the caveat that the user will now only be asked for ModMaker. Texplorer and TPFTools will not note this, but I guess that doesn't matter since A) Texplorer should extract at the treegen, and B) there won't be any modified DLC to trigger the extraction.
3. At this time, it's just too bad. Ideally that's what would happen, but this takes the pain out for the future with little effort.
   If I eventually get around to rewriting things, this will probably change, but for now, too much effort.

**Comment by ghost** [comment]
#3 -- Okay, then just make sure the warning message to the user is clear that _total DLC extraction_ is mandatory. All or none.

**Comment by KFreon** [comment]
I thought I worded it as all?
I'll capitalise it or something to make sure.

**Comment by ghost** [comment]
@Kfreon -- See update to #132 .

**Comment by ghost** [comment]
Doesn't look like it's fixed.

I'm testing applying a .mod to a DLC mod and I triggered this message when choosing "Run All":

![mm_dlcmessage](https://cloud.githubusercontent.com/assets/13645804/13829472/75fbd7e6-eb84-11e5-991f-ae835ef3b68d.PNG)

In my case, all my DLC are already extracted, so the message isn't valuable and confusing. It's what I reported as No. 1 in the OP above.

This Issue also of course relates to #235 and the whole DLC extraction change. Namely, that part of the point of moving DLC extraction to the start of the toolset, was so that MM and Texplorer didn't have to warn the user about this stuff anymore.

**Comment by KFreon** [comment]
Fixed.

**Comment by ghost** [comment]
I'm _sort of_ still getting this message.

I'm now getting the new message about "Jobs containing DLC references, go back and extract now" for the same freshly-made mod file affecting a DLC mod. Yet, ALL of my DLC are extracted.

No information in the debug output related to the message, so I'm not sure what's causing it. Anything I can do to help you better locate the issue?

**Comment by KFreon** [comment]
It's that annoying __metadata folder. 
Fixed I think.

**Comment by ghost** [comment]
I'll say this is verified in 745. New issue for the false positive of the DLC issue has been moved to #269.
