### ISSUE TITLE
REV 728 scaling failure TPF/DDS tools 3.0

### ISSUE THREAD

**Issue by forgetti** [ME3Explorer/ME3Explorer#149]
the scaling in this version is buggered. I can't actually use any features of tpf/dds tools 3.0 since the scaling has hidden almost everything

visual issue here http://i.imgur.com/3O90oVl.jpg

I'm running at 1680X1050 resolution

**Comment by KFreon** [comment]
Wait this is a new thing?

**Comment by forgetti** [comment]
![capture](https://cloud.githubusercontent.com/assets/16586137/12371354/8ceee0e2-bc95-11e5-9113-988b46cadbba.JPG) and it's not just something that hides the buttons when no tpf is selected. they're even hidden when you've got one loaded

**Comment by starkgate** [comment]
I can confirm this also happens for me. I have a native resolution of 3840x1080, changing it to 1920x1080 or 1366x768 didn't change anything.

**Comment by CreeperLava** [comment]
The buttons that appear when selecting a texture are also invisible in Texplorer.

**Comment by KFreon** [comment]
Is it something I accidently set on the exe itself? 
I haven't changed anything else...
EDIT: Also I get those buttons behaving correctly-ish at 4k.

**Comment by KFreon** [comment]
I think I've found out what the problem is. VS appears to have scaled all the pixel sizes for me. i.e. the dimensions of everything set in pixels (which shouldn't change) have been scaled to my 4k screen. Hence for everyone else they're enormously incorrect.
Think I've fixed it...

Question though: Does this happen for Texplorer?

**Comment by starkgate** [comment]
No, there's no problem with Texplorer.

**Comment by starkgate** [comment]
Some news, in rev729 (above) vs 718 (below) :
![b1](https://cloud.githubusercontent.com/assets/12874678/12376736/e24184aa-bd03-11e5-8f7b-dab91c76c4cd.png)
![b2](https://cloud.githubusercontent.com/assets/12874678/12376737/e241dd88-bd03-11e5-9898-e4a573f2da1d.png)

**Comment by KFreon** [comment]
Ah dammit.

**Comment by forgetti** [comment]
I thought something else was missing

**Comment by starkgate** [comment]
We're getting closer in rev730, but the Analyse/Install Valid/... still aren't visible :/. On the bright side, the right panel is now correct.

**Comment by ghost** [comment]
Not quite fixed yet. Now we have a different set of scaling issues:

![tpftoolsgui](https://cloud.githubusercontent.com/assets/13645804/13017559/ac769a1a-d179-11e5-92eb-0a62713c66d5.PNG)
1. Above the preview window, at the very top, the first line of text is getting cut off.
2. The two main panes are no longer resizing. Not the jobs or preview pane. A giant white space appears under both if the window is resized, and the preview image doesn't scale at all. This isn't how it used to work, so I'm guessing it isn't intended, lol.

**Comment by starkgate** [comment]
Same results as giftfish here, resizing the window doesn't change it's content. I see you adopted my method to highlight problems on screenshots gift, nice^^.

**Comment by ghost** [comment]
@CreeperLava -- Ha ha. Nope, didn't get it from you, just naturally happened as I switched from one kind of screencapture program to another over the past year or so. With the new one, I can edit inside it, so I don't have to open the image in GIMP... which is when I'd be very neat put nice boxes around things and typed text, lol.

I have to say, the scribble method _is_ very attractive, though :)

**Comment by KFreon** [comment]
This is most vexing.
WinForms DPI can go _insert cursing here_

**Comment by starkgate** [comment]
Confirmed to work in rev735. Scaling works fine, no more hidden buttons either.

**Comment by ghost** [comment]
Nope, not for me.

Here's what mine looks like, as I scale the window:

![tpftools_scale1](https://cloud.githubusercontent.com/assets/13645804/13082521/e0868554-d485-11e5-885f-d94caed3dd31.PNG)
![tpftools_scale2](https://cloud.githubusercontent.com/assets/13645804/13082520/e083fe60-d485-11e5-9c1b-01a1beb0d75e.PNG)

@KFreon -- I think we need a bit of a new strategy on this. I'm not sure the "flying blind" is going to get us there. Or, it's going to take so long we're going to go a bit insane.

First, let me tag @SirCxyrtyx and @HeffU . Do you guys have any info on how these new scaling issues can be fixed?

Second, is there any type of Winforms coders forum that we could ask on; something like that, that could point us in a better direction?

Third, if the scaling cannot be fixed, then we have to consider the possibility of ditching Winforms. The obvious problem with this is the amount of work it will take to recode the GUI for every tool. @HeffU and I were planning on working together to do this after the stable -- obviously trying to do it now isn't optimal, as he's pretty busy again.

**Comment by starkgate** [comment]
If you mean the 'problems' with the preview, yes I get the same. Not a major issue though.

**Comment by ghost** [comment]
@CreeperLava -- Well, it sort of is, though. It's not working as intended, and not working like it was before K's monitor change.

Here's what it looks like when I first open the tool, load a TPF, and select a texture:

![tpftoolsscalebase](https://cloud.githubusercontent.com/assets/13645804/13082876/5282c450-d487-11e5-897a-49c8019767b7.PNG)

This is without any resizing at all. So, in other words, every time a user like me opens the tool, they not only have to resize the entire window to be able to see the whole preview, they have to adjust the divider b/n the two panes.

Having to do that every time it's opened will get old, very quickly. Definitely needs to be fixed.

**Comment by ghost** [comment]
Decided I'd just move this additional info into a different post with it's own screenshots:

The scaling issue is also preventing scroll bars from appearing in the PCC-selection area. If a texture affects a bunch of PCCs, the only way I can get to them is by scaling the window, rather than scrolling. And, then, I eventually run out of room (dictated by my monitor's size), and not all can be displayed. Here's a comparison of 727 and 735:

![tpftools727_735](https://cloud.githubusercontent.com/assets/13645804/13083463/f33e8be8-d489-11e5-9e8b-6571763e3574.PNG)

You'll also note that the "Modding ME3" button is gone in r735. That will appear if the window is sized larger, but it's **not** getting buried under the dropdown arrow. 

EDIT: Uh, by "gone" I mean upon scaling. It is present if the window is made large enough, which you can see in my previous screenshots.

**Comment by KFreon** [comment]
@giftfish Regarding ditching Winforms.
There is no way to describe how much work there is changing out of winforms in a sensible manner.
We could dodgy up a monstrosity that kinda worked I suppose, but it'd be that thing where it's more ethical to just put it out of it's misery.

Switching from winforms to WPF is like saying "imma switch this car engine over from diesel to petrol". 
It sounds like it should be easy, just a different thing here and there right? 
Unfortunately it's a little more fundamental then that.

At this stage, it's still easier to beat this dead horse till it fits in the box, rather than go to town and get a new shiny horse...

I plan on plugging in my other PC, which runs at the old resolution so I should be able to go there to fix things.

**Comment by ghost** [comment]
@KFreon -- I was assuming it would be hella lot of work; I didn't think it was going to be a small thing. My discussions with Heff made that clear. I suggested it only as a last resort, as the current "flying blind" method isn't working well.

Sounds like plugging in your old PC might solve it, but then my question is... is the problem solved? Or, is it still actually there and we just don't know about it, since your resolution will now again be similar to most other people.

**Comment by KFreon** [comment]
@giftfish -- I'm talking months for the toolset. Just thinking it's not really an option for the stable.
Either way, I believe the problem is on the development end. So when I build it at a different DPI to everyone else, it looks fine for me, but when it uses those values to adjust, it gets them wrong because the DPI's are different.

That should be fixed if I use the standard Winforms DPI that it's used to.
We'll find out anyway.

**Comment by ghost** [comment]
@KFreon - Yeah, I get it. I'm not saying it was the best solution. I was only suggesting it if there was **literally** no other solution. Absolute, 100%, last resort. No other options.

So, let's hope this other solution works.

**Comment by KFreon** [comment]
See #171

**Comment by ghost** [comment]
And, we still have a small issue here that didn't exist prior to the "4K scaling issues from hell":

![tpftools_moarscaling](https://cloud.githubusercontent.com/assets/13645804/13222713/0f4b9d16-d936-11e5-96e1-7a62022e93b8.PNG)

I can verify that on my standard 1920x1080 display, every other scaling issue with Texplorer, TPF Tools, and ModMaker has been fixed. The TPF Tools preview area still isn't exactly like it was, but it's close.

**Comment by KFreon** [comment]
Fixed I think.

**Comment by ghost** [comment]
And, not fixed... or at least, not fixed anymore:

![tpftools_gui bug](https://cloud.githubusercontent.com/assets/13645804/14066114/8ddf89c8-f3f6-11e5-9fe7-80ae237bb20a.PNG)

**Comment by starkgate** [comment]
@giftfish I don't have this issue, whatever the resolution I choose. Scaling has never been so perfect on my side :).

**Comment by ghost** [comment]
Oh sure, rub it in, Creeper, lol :P

**Comment by starkgate** [comment]
No problem, glad to help :).

**Comment by KFreon** [comment]
Fixed.

**Comment by ghost** [comment]
Yay. Fixed again.

Verified in rev748.
