### ISSUE TITLE
r733, Texplorer post-replace, null error, no bottom menu

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#181]
So, this is a bit weird.

Was getting ready to close the tool after doing a test replacement (the one that resulted in issue #180 , and I clicked on the thumbnail of the texture I had replaced. This resulted in the error below:

![texplorer_nullpostreplace](https://cloud.githubusercontent.com/assets/13645804/13035650/eaa984c8-d309-11e5-900c-706ebcd7981f.PNG)

More interestingly, selecting the thumbnail didn't trigger the appearance of the bottom menu. It won't appear when selecting any other thumb, either. To get it to reappear, you have to close and reopen the tool.

**Comment by KFreon** [comment]
Fixed crash and menu not showing up.

**Comment by ghost** [comment]
This issue is not fixed. Still present in r745. Texplorer is unusable post-texture replacement, unless you close and re-open the tool.

**Comment by KFreon** [comment]
Hrm works for me.
Can you be more specific? Crash and/or menu not working?

**Comment by ghost** [comment]
@KFreon -- There's no debug output, just the error window in the screenshot in the OP. 

It's almost like Texplorer needs to close/reload to correctly read the edited tree.bin file. Or the file itself needs to be reloaded, which is only done upon re-opening the tool. 

It actually reminds me of some older, similar errors in other toolset tools. For example, the Conditionals Editor, which reads only the CND files, used to throw a similar error if you added in a new conditional ID, and then selected to view the expression. If you manually re-opened the file, then the error would go away. What fixed it was WV forcing the tool to reload the file automatically when a new CND was added.

Like I said, I don't know if that's exactly what's happening here, but it seems similar, since closing/opening the tool fixes the problem.

**Comment by ghost** [comment]
Not sure what the problem was, @KFreon , but this can be closed. Rectified in rev746.
