### ISSUE TITLE
r742, ModMaker, Various .mod install errors

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#242]
So, I decided to test two things:
1. Installing a .mod to a DLC mod, created specifically for it.
2. Installing a .mod that is supposed to add to the name list.

I got this error:

![mmerrordlcmod](https://cloud.githubusercontent.com/assets/13645804/13829648/5f7bed8e-eb85-11e5-8fa3-9f1f92a1ca6f.PNG)

I made the mod using the PCC Compare feature, which worked great. No problem creating the .mod. But, it won't apply properly to the file in the DLC mod (BackOff).

I'd attach the mod, but for some reason Git doesn't want to let me attach ZIP files. No idea why; it's supposed to allow them. Nothing in the debug window that's useful.

**Comment by ghost** [comment]
@KFreon -- Was just looking at this again and noticed something in the screenshot. MM is trying to use _PCC Replacement._ 

It should say "Binary Replacement", like this:

![mmbinary](https://cloud.githubusercontent.com/assets/13645804/13833651/19f922ac-eba5-11e5-8842-7bf5dcd76b93.PNG)

So, maybe the real problem is that PCC Compare isn't working right?

**Comment by KFreon** [comment]
I'd say that's just me naming things wrong, but I'l change it to make consistent.

**Comment by ghost** [comment]
And, another error for the same mod file as the first one in the OP, but freshly made with PCC Compare in r744:

![dlcmodfile_install](https://cloud.githubusercontent.com/assets/13645804/13994096/791e45b0-f0e0-11e5-9d18-0d4faf72f10f.PNG)

"Binary Replacement" is now fine, though :)

[Pastebin of script](http://pastebin.com/4kGkRzw8)

**Comment by KFreon** [comment]
Think this is fixed. There was another script bug after that one :)

**Comment by ghost** [comment]
Nope, this is still not fixed. It's just one different bug after another. 

Is there any way to troubleshoot these problems more thoroughly as they're addressed? It feels like we could go on like this forever, which isn't practical; it's like the scaling issue were having.

Two mods and the same issue (this time).

This mod file was created by selecting a specific job for extraction from ELE's original mod (which also has to have the script automatically updated). It affects only the CE DLC:
![dlcmod_install](https://cloud.githubusercontent.com/assets/13645804/14047902/01f03c80-f268-11e5-9e2f-656440383a48.PNG)

So, there's actually room for error during two steps for the above mod: when ELE's original mod is updated during the loading process, and when the single job is dumped into a new mod. Not sure if that helps you figure out the problem or not, K.

The other issue I won't provide a screenshot of since the error itself is almost identical (Line 51 instead of 49). However, it's generated via PCC Compare and affects a DLC mod.

**Comment by KFreon** [comment]
I swear this didn't happen when I tested it last time. 
This one is fixed now.

**Comment by ghost** [comment]
And, there's another new one:

![mm_dlcagain](https://cloud.githubusercontent.com/assets/13645804/14066239/0f99001e-f3f9-11e5-9d8f-f616e1d93a2d.PNG)

This same issue has been open/closed 4 times now. K, there must be a smarter, better, more efficient way to do this. One thing I want to be clear about is that what's happening basically breaks Mod Maker; I can't install _anything_. That's _including_ stuff to the base game.

@SirCxyrtyx , if you have any ideas, I'd love to hear them.

**Comment by SirCxyrtyx** [comment]
I tested it, and it seems to run fine now, so fingers crossed that this is the end.

**Comment by ghost** [comment]
Oh, thank flippin god, I really hope so, lol.

**Comment by KFreon** [comment]
I do wonder why these errors don't show up for me.
It's troubling.
I guess I just suck at programming.

**Comment by ghost** [comment]
@KFreon -- Is it possible it's dependent on which version of Windows? Nephthysmoon did some testing for 746 and she got the same error I did at that point, so I'm fairly sure it's not me >.<

I can certainly understand why them not showing up for you is troubling -- I'd like to know why they don't, too!

**Comment by KFreon** [comment]
Eh as long as it works for now.
Maybe I had it pointing at the new library...

**Comment by ghost** [comment]
@KFreon -- Well, we'll find out on the next rev >.>

**Comment by ghost** [comment]
@SirCxyrtyx , @KFreon -- Good news! This works.

I have _finally_, after several revs, been able to install a mod. However, something is now broken with PCC Compare again (#138).

**Comment by ghost** [comment]
@SirCxyrtyx , @KFreon -- Now that .mod scripting is finally fixed, I've been able to verify that .mods (well, at least 1) are being properly installed. Yay.

Here's ELE's Varren on the Normandy .mod in action:

![masseffect3 2016-04-08 09-40-39-50](https://cloud.githubusercontent.com/assets/13645804/14391133/23e3ba3a-fd6f-11e5-891e-455423bcd13b.png)

Something interesting about the textures used by this mesh. 

The game only reads the BioD_Nor_500.pcc for the mesh, but it reads the textures from 3 different files: Nor_500, Nor_300, and Nor001Global. 

Initially, I tried only replacing the textures inside Nor500, and got this result:

![masseffect3 2016-04-08 08-59-55-48](https://cloud.githubusercontent.com/assets/13645804/14391239/c16dc020-fd6f-11e5-8541-e9a593fb9ec9.png)

Then, I replaced them inside the other two files, and it still didn't work. From there, I checked my DLC. 

While Nor500 wasn't modded by any of my DLC mods, the other two were. Once I disabled those, I could view the new textures properly.

So, it seems that at least sometimes, ME3 goes the route of ME1 and loads textures and meshes from multiple files to generate the in-game actor. This obviously creates problems with de-selecting PCCs. I'd guess this is more common for static meshes and non-speaking actors associated with specific levels (Normandy, Citadel, etc). In the case of a texture being used on a mission-type level (Grissom) _and_ on the Normandy, I'd doubt there would be this type of cross-use.

Regardless, it complicates things a bit, so I'll need to add something about it in the wiki.
