### ISSUE TITLE
r746, Texplorer, Miscalculating Mips

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#270]
@KFreon -- Pretty sure we've had this problem before, but I figured it was less confusing to open a new issue.

I didn't have this problem in the last rev, but I do in this rev. Texplorer won't let me replace a texture of the identical size, with identical mips. 1024x1024 textures have 11 mips, from 1x1 to 1024x1024. Texplorer seems to think it should have 12: 
![tex_mips](https://cloud.githubusercontent.com/assets/13645804/14049804/d9f7c236-f274-11e5-8be8-57b362a36e85.PNG)
Verified that the mips in GIMP and 11 of all the proper sizes are indeed there. 12 mips are required for 2048x2048, not 1024x1024.

**Comment by ghost** [comment]
FYI, this may only affect 1024x1024. I just did a replace for ME1 using a 2048x2048 texture and didn't get the mips error.

**Comment by KFreon** [comment]
Think this is fixed. Was due to a null mip on top. 
Curious that this has only been found now...

**Comment by ghost** [comment]
@Kfreon -- I iz the bug-finding queen.

...I really, really don't want to be. >.>

**Comment by ghost** [comment]
And, not fixed.

Now, it thinks GUI textures need more than 1 mip. I'll try to text out several different sizes and see if anything else is borked.

![miperror_gui](https://cloud.githubusercontent.com/assets/13645804/14066444/2852164a-f3fe-11e5-8fa0-f176b87d2f68.PNG)

EDIT: So, definite errors for:
1. 512x256 > 1024x256 (1/1; wtf)
2. 1024x1024 > 1024 (12/11; same as initial screenshot)
3. 512x512 > 1024 (11/11; wtf)

I'd say everything likely needs to be checked, @KFreon .

**Comment by ghost** [comment]
Hm. Just had another thought about this.

I copied my trees over to speed testing. Is it possible that a tree built on the rev would correct this problem, or no?

**Comment by KFreon** [comment]
A new tree shouldn't be necessary for this since it gets details from the game files each time either way.
I'll look into it.

**Comment by KFreon** [comment]
The 1/1 ones are fixed but that other one, I changed fine.
I just noticed that it's expecting 12 mips for a 1024 texture, which is wrong...

EDIT: Original mipcount is in the tree. Can't remember why it's there, but if you copied trees this could be the problem.
It could have been at the time that the mip counter was incorrect.

**Comment by ghost** [comment]
Lol. @KFreon, the "expecting 12 mips for 1024" is exacting what's reported in the OP of this issue. Silly K.

I'll rebuild trees today, after I do some more texture installation testing in ME1 and ME2 (with TPF Tools). We'll see if that fixes it :)

**Comment by ghost** [comment]
@KFreon -- Okay, it's definitely not the old tree. Slightly different results, though.

So, now it's giving the proper expected and new mips -- and they match -- but it won't allow the replace. Just like the GUI texture replace I posted above, but with the same texture replacement for Ashley's CE armor I tried in the OP:

![mipsagain](https://cloud.githubusercontent.com/assets/13645804/14084016/9c7d1a18-f4cd-11e5-91a0-8aa64987f758.PNG)

**Comment by ghost** [comment]
@KFreon -- What happened to be the problem with this, btw? How was it was getting the proper mip count, but not recognizing it as the proper count? Just curious :)

**Comment by KFreon** [comment]
The check for if there were enough mips was doing > only, instead of >=.
So it'd only work when there were more mips than the original and no just enough.

**Comment by ghost** [comment]
Ahhh, gotcha.

**Comment by ghost** [comment]
This seems fixed :D

Verified in rev748.
