### ISSUE TITLE
rev748 ARGB issues

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#296]
First issue is with the preview. The picture below shows what the preview looks like after autofixing DXT1 to ARGB. The autofixed texture displays fine (ie white on black) outside of TPF/DDS, but TPF Tools seems to prefer displaying white on green instead.
![capture](https://cloud.githubusercontent.com/assets/12874678/14358466/4c6c6eca-fced-11e5-9a0d-452a56e1e758.PNG)

Second issue : the alpha. Below are a few pictures that show how the vanilla, modded unfixed and modded fixed textures look like in Photoshop. The problem is a white alpha in the autofixed ARGB texture.
![capture3](https://cloud.githubusercontent.com/assets/12874678/14358465/4c6c0782-fced-11e5-8a98-03dbcdd98e34.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/14358468/4c6f3056-fced-11e5-8e61-de3f0918afe8.PNG)
![capture4](https://cloud.githubusercontent.com/assets/12874678/14358467/4c6dfe52-fced-11e5-99df-65fdc7860909.PNG)

Testing files : http://filebin.ca/2cxELJA02dlX

**Comment by ghost** [comment]
FYI, any fixes to this issue need to account for #267, to ensure nothing there breaks again.

**Comment by ghost** [comment]
#299 is likely related to this issue.

**Comment by KFreon** [comment]
Well this is interesting...
![image](https://cloud.githubusercontent.com/assets/7845997/14377897/9f7009c4-fdb5-11e5-9c52-99f92161eb83.png)

I tried converting in ImageEngine too and nada. Works fine. 
Wonder if it's a Windows 7 thing, but more importantly, wtf is with the format difference?

**Comment by starkgate** [comment]
That IS definitely odd. I'm using the binary release, if that makes a difference ?

**Comment by KFreon** [comment]
Shouldn't. You made a new tree recently?
@giftfish Do you mind checking what format this texture is in your tree?

**Comment by KFreon** [comment]
Just for my own reference, the tree starts off with the correct format and somehow loses it later on. Not sure whether its saving or loading.

**Comment by ghost** [comment]
Also, Creeper mentioned yesterday he was using an imported tree. Not sure if he ended up building a new one or not.

I know porting trees saves time, but certain texture data is saved into the tree that impacts the display of information. I think the best bet for testers is to start each rev with building new trees. Plus, it then tests treebuilding.

Will check after I grab my coffee and update this post.

**Comment by ghost** [comment]
Yep, mine turns green in the preview, also.

The "vanilla" versus "unfix" texture have a slight difference. Looks like... I think they are sideburns?... that become more pixelated.

**Comment by starkgate** [comment]
@giftfish See #304 :)

**Comment by KFreon** [comment]
Should be fixed now.

**Comment by ghost** [comment]
@Kfreon -- Not fixed, and something weird is also going on when autofixing one versus all.

Here's post analyzing:
![argb_analyze](https://cloud.githubusercontent.com/assets/13645804/14412019/0919db4a-ff0d-11e5-8405-aa474466a5d6.PNG)

Here's after just autofixing the bottom texture:
![argb_abottomautofixed](https://cloud.githubusercontent.com/assets/13645804/14412020/14f167d0-ff0d-11e5-9239-b74f1721ef96.PNG)

This looks fine. Both the green is gone and the sideburn isn't as pixelated like in Creepers initial post.

But here's the bottom texture after using Autofix All:
![argb_allautofixed](https://cloud.githubusercontent.com/assets/13645804/14412022/1fd8ed62-ff0d-11e5-9f3d-a8d239791ad0.PNG)

Green again. I can't really tell if the pixelation is back or not, since there's not enough of a contrast between the green and white.

**Comment by KFreon** [comment]
First weird thing, how'd you even get 3 of the same texture past Analysis?
They should be detected as File Duplicates at least...

I'll look into the green thing. Makes it easier to find if it's constrained to multiple simultaneous autofix.

**Comment by ghost** [comment]
@KFreon -- Uh... no idea. I just downloaded Creeper's test files, loaded them all up in TPF Tools, and hit "Analyze". But, yeah, that's a very good point, lol. They all have the same hash assigned. No idea why the toolset doesn't seem to know that...

**Comment by KFreon** [comment]
Some of them are likely broken. He includes all relevant textures, hence some don't work.
That could be the cause, but either way, the one with "unfix" in the title is the correct one.

**Comment by ghost** [comment]
Well, you can download and try them yourself in case I did something wrong. The issue should be replicable. If not, that's a whole 'nother problem.

**Comment by KFreon** [comment]
Yeah but what I mean is the broken one might have something in it making it green, which doesn't happen with a proper texture.
Either way, I'll look into it.

**Comment by ghost** [comment]
@KFreon -- Looking into this more with new textures extracted/edited with the current rev.
1. In a new tree built with the prebuild, the texture above is indeed ARGB when viewed in Texplorer. (Sorry, I didn't see your question about this at first).
2. The issue with the green is gone. I don't experience this with textures autofixed, extracted, and then reloaded into TPF Tools with this rev. I did a 4-way comparision using two types of autofixes and formats compared to vanilla and none were green.
3. The issue with the alpha that Creeper reports in the ARGB to DXT1 conversion remains. This is due to autofix:

![final_compare](https://cloud.githubusercontent.com/assets/13645804/14432977/4aaf9e82-ffc1-11e5-98c9-bcb1b6260374.PNG)

Here's what we have:
- bottom right = vanilla
- bottom left = vanilla ARGB converted to DXT1 in Image Engine using default alpha settings
- top right = the bottom right texture, autofixed in TPF Tools to generate MIPs
- top left = the bottom left texture, autofixed in TPF Tools to change to ARGB

It seems like autofix is not saving the alpha properly -- at least not with DXT1 textures. The alpha layer for those two when highlighted is a pure white box, just like Creeper's example above.

The sideburn pixelation issue is much reduced. It's not perfect, but I don't see it as something we should keep trying to improve and delay the stable for. If people want perfect, they can edit manually.

---

As far as the hashes, it seems like the tool is only _sort of_ recognizing the duplicate hashes. It only leaves one checked after autofix, which is good:

![loaded_compare2](https://cloud.githubusercontent.com/assets/13645804/14433478/50d13440-ffc3-11e5-9337-be4c115815be.PNG)

However, what TPF Tools used to do was "nest" identical textures with a branching scheme, so they were all confined to the same location. This also made it easier to chose one from all available, and is what "Promote Duplicate" is for. I thought maybe this was an artifact of not having other textures loaded, so I also loaded the Ashley Legacy mod TPF. Here's what happens after analyzing:

![loaded_compare3](https://cloud.githubusercontent.com/assets/13645804/14433576/a1b6ea1c-ffc3-11e5-9570-7cf427b56986.PNG)

The ones that are placed into the branching scheme and are recognized as duplicates are the ones that have been _autofixed by TPF Tools during this session_. They are in the toolset's temp autofix directory. For some reason the other 2 are NOT recognized as duplicates, despite identical hashes.

This seems like the more problematic issue, actually.

**Comment by KFreon** [comment]
GIMP is looking to be too unreliable to use as a tool of comparison when it comes to DDS.
![image](https://cloud.githubusercontent.com/assets/7845997/14452841/b1dc0762-00d4-11e6-94ad-a9eccea25e7a.png)

Now the hash thing.
Originally, it was set up to remove textures with the same hash and filename, i.e. when a tpf contained two of the same textures from various mod creators (usually the filename was the same)
In your tests, the filenames were different and thus were considered different textures.

I figure this is the way you want it to work? I can't entirely remember why the filename was important at the time, but it was...

**Comment by ghost** [comment]
@KFreon -- 
1. **Alpha autofix issue** -- I don't think this had anything to do with GIMP; Creeper had the same results in his test with PS. I verified them with GIMP. Creeper tested with r748. I tested with the prebuild you linked a couple day ago. Did you test with the same pre-build, or have you made additional changes to the code since then? When checking for replication the same toolset version obviously must be used.
2. **Hashes/Duplicates** -- The file name should be irrelevant. No two mod authors are going to use the exact same file names when making a TPF or DDS; why would they? The tool should detect duplicates based on one or two things: hash or Texplorer package name (post-analyze name). These are the only two things that will be consistent across textures that are indeed identical.

I'm going to re-open the issue to make sure the thing with the duplicates is fixed. Detecting by the pre-analyze file name that you described is absolutely not going to detect duplicates properly. 

Hashes seem like the best thing to use, as don't tree duplicates share hashes but have different Texplorer package names?

**Comment by ghost** [comment]
@CreeperLava -- If it's possible for you to re-test the alpha issue with the new pre-build K just posted on the WIP Stable thread on ME3Exp, it sounds like it would be a good idea.

I can test it again, but I don't think that's going to do us much good.

**Comment by starkgate** [comment]
I can't check it right now, you'll have to wait for a week or so until I have access to windows.

**Comment by ghost** [comment]
@CreeperLava -- We'll see. The stable might be out by then. If there's no other problems after these final 3 issues (and there really, really shouldn't be), we might be releasing this weekend.

**Comment by alvarome** [comment]
Hi:

I have nothing to add  about those issues but I also wanted to let you know that I find all that info about toolset internals -I mean, how is handling texture operations based on hash or name- very interesting.

I have to say that I always thought any texture operation would be defined by its hash as it is unique to each texture -no matter tree duplicates-. So I find surprising to discover that name was relevant also here.

So thank you for sharing!
Alvaro

EDIT I have to say I´m still confused.

[...] Hashes/Duplicates -- The file name should be irrelevant. No two mod authors are going to use the exact same file names when making a TPF or DDS; why would they? [...]

From my -you know, veeeeery basic toolset understanding- the file name IS irrelevant. No matter the file name because the name used/displayed at TPF/DDS tools is the one from the tree.bin. Am I worng here?

But then, if previous is correct -something I do not know- I assume that the need to check the name is just for tree duplicates?

Sorry for kidnapping the post... just inquiring minds want to know! ;) I can place this question at ME3Explorer toolset help forum if you think that´s a better place to do it!

**Comment by KFreon** [comment]
@giftfish - I used the build I recently posted on the forums.
So to reiterate, I can't replicate it. If one of you can retest with the recent test build, that might either confirm it fixed or maybe it's somehow an issue with Windows 7. (I believe you're both on win7)

Also textures were often kept as the old texmod extracted name back in the day when I wrote that part of the code. Different named textures were the exception, not the rule.
But that's fixed now, right?

@alvarome - Should probably be a question for the forums, but the name check was for FILE duplicates i.e. you've loaded a tpf from ottemis and ele who both modify the same texture and, in the old days, the filenames were the same, so they had to be treated as the same Texture. Both couldn't be installed, but you could choose between them.

**Comment by ghost** [comment]
> Also textures were often kept as the old texmod extracted name back in the day when I wrote that part of the code. Different named textures were the exception, not the rule.
> But that's fixed now, right?

@KFreon -- No, it's not fixed now. Well, it might be, but we don't know, since TPF Tools is hanging on matching hashes (see #294 ). But debug says "Finding duplicates" at the hang, which indicates there's a problem with duplicates detection.

**Comment by KFreon** [comment]
Ohh right. Ok, I'll try fixing that then.

**Comment by ghost** [comment]
@KFreon -- #292, #294, #296, and #305 are all easy to test, so if you can link me a new prebuild, I can test them tonight :)

Be sure you see my post above about the proper way to detect duplicates, though. I'm still not clear how you've changed that and what I should expect :)

**Comment by KFreon** [comment]
I'm at work, so if I understand timezones, that'll be tomorrow for you :P 

All I did for hashes is removed the bar of filename as a duplicate detection. In your test, there should be 1 top, and 2 children duplicates.

**Comment by ghost** [comment]
Okay, got it.

Tomorrow, it is, then! Stupid work always gets in the way -_-

**Comment by ghost** [comment]
@KFreon -- We're almost there.

Duplicate detection is finally working. Upon loading 4 textures into TPF Tools with different names and the same hashes, this happens after analyzing:

![duplicates_dimen](https://cloud.githubusercontent.com/assets/13645804/14504883/7cb17468-016b-11e6-899d-8cd8ff207e82.PNG)

We now have a new problem: they are incorrectly getting flagged with "dimensions". The mips and format flags are correct. The dimensions flags are not. These are all square textures of the proper size, and the previous prebuilds didn't flag them for dimensions. Debug gives some indication of the problem:

![duplicates_dimen_debug](https://cloud.githubusercontent.com/assets/13645804/14504982/fc635276-016b-11e6-99cc-e53a7798d73e.PNG)

Obviously there's something to fix here, but please be very careful. There have been probably 2-6 other issues recently that have involved dimension detection and have been fixed; we don't want this fix to negatively affect those others.

Looks like we need one final prebuild to test the fix for this, K. It's the final issue :D

**Comment by ghost** [comment]
@KFreon -- Damn. You keep fixing one thing, and then something else happens. Now duplicates and dimensions are fixed, but autofix thinks there's nothing to fix:

![autofixdetectfail](https://cloud.githubusercontent.com/assets/13645804/14532005/4bc4f9e8-0214-11e6-8d8b-30d2cdc6ade5.PNG)

What's happening here seems to be a result of having duplicate textures that _don't_ need fixing. If I load up a single texture that needs fixing, it fixes fine:

![needsaf](https://cloud.githubusercontent.com/assets/13645804/14532065/8aeb342a-0214-11e6-8432-067fd69e63d9.PNG)
![af_success](https://cloud.githubusercontent.com/assets/13645804/14532071/8fd4baa6-0214-11e6-8576-ed5753c4de41.PNG)

If I go back to the first 4 textures I used and _only_ load the ones that need fixing, autofix only fixes the first one and leaves the second one borked:

![autofix weird](https://cloud.githubusercontent.com/assets/13645804/14532165/f82007d2-0214-11e6-9725-ce4f9ec5be58.PNG)

To summarize:
- If the first duplicate hash texture autofix encounters doesn't need fixing, it will not autofix any other duplicates -- _even if they need to be fixed_
- If the first duplicate hash texture autofix encounters does need fixing, it will fix that one and not any others -- _even if they need to be fixed_

We can leave it this way, but it means users will not be able to promote valid textures and use them, even if they happen to prefer a different one that's improperly formatted.

**Comment by starkgate** [comment]
Just checking the obvious, you did click on Run Autofix All ? Because all checkboxes aren't checked, thus using the Autofix button won't fix everything.

**Comment by ghost** [comment]
@CreeperLava -- All the screenshots except for the first one of EDI's eye are post-autofix, which is why they are unchecked.

Good idea nonetheless, so I did go back and check that to be sure. The same thing still happens, regardless of using Autofix All or Autofix Checked.

**Comment by KFreon** [comment]
This behaviour is intended. I don't want it fixing every duplicate texture since:
1) They don't get installed.
2) Almost no one ever switches duplicates from their original positions. 

I suppose that could be confusing. I'm tempted to remove the checks done on duplicates entirely, until they're promoted to top.
I suppose they probably could be fixed...

**Comment by starkgate** [comment]
> 2) Almost no one ever switches duplicates from their original positions.

True, I never used that functionality actually. If it's not too hard to implement, I see no reason to not fix everything though.

**Comment by ghost** [comment]
@KFreon -- Well, I don't know about "almost nobody switches them"; I don't think we have data to support that. BUT, if we don't want to fix them, that's fine by me.

If you fix it, there's a good chance something else will be affected and it will cause new problems. I think we've fixed enough things for the stable.

EDIT: And if we don't fix it, I'll just start a new issue and tag it as an enhancement, so you can catch it in the re-write.

**Comment by ghost** [comment]
AND, if you don't want to fix it, AND if there's no other issues that have sneaked through and I need to test (like #313), then we are ready for v749, the final test for the stable.

**Comment by SirCxyrtyx** [comment]
> the final test for the stable.

Could it be? Is the fabled day upon us at long last?

**Comment by ghost** [comment]
@SirCxyrtyx -- Omg, don't jinx it!

**Comment by KFreon** [comment]
Yeah, I don't think I'll bother fixing that. 
To get around it, you can promote the duplicate then just fix it again.

So....749 is on the horizon :D

**Comment by ghost** [comment]
@KFreon -- Very true. Just tried that, so good call.

I'll submit a new issue for it so we can keep track, but will _not_ tag it with the 110 milestone, so it should _not_ be fixed for the stable :)
