### ISSUE TITLE
rev748 TPF Rebuild Texmod

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#305]
The MEResults.log seems to be generated wrongly : everything before the underscore in the name of the texture is cropped.
Like that :

```
0x8BF84879|_0x8BF84879.dds
0xE224ED25|_0xE224ED25.dds
0xE5100929|_0xE5100929.dds
0xA12623F4|_0xA12623F4.dds
0xCF8B7094|_0xCF8B7094.dds
0xC24409CC|_0xC24409CC.dds
0x5DEBFB67|_0x5DEBFB67.dds
0xCF0810CD|_0xCF0810CD.dds
```

In this case, it should be :

```
0x8BF84879|MASSEFFECT2.EXE_0x8BF84879.dds
0xE224ED25|MASSEFFECT2.EXE_0xE224ED25.dds
0xE5100929|MASSEFFECT2.EXE_0xE5100929.dds
0xA12623F4|MASSEFFECT2.EXE_0xA12623F4.dds
0xCF8B7094|MASSEFFECT2.EXE_0xCF8B7094.dds
0xC24409CC|MASSEFFECT2.EXE_0xC24409CC.dds
0x5DEBFB67|MASSEFFECT2.EXE_0x5DEBFB67.dds
0xCF0810CD|MASSEFFECT2.EXE_0xCF0810CD.dds
```

**Comment by KFreon** [comment]
That's happening because the texture name is empty.
More details on the situtation? Analysed etc?

**Comment by starkgate** [comment]
I think I did not analyse it, and I chose to rebuild TPF only with checked.

**Comment by ghost** [comment]
@KFreon -- I can try to replicate this when I test the pre-build, but see my comment in #299 first. It's possible something else is going on with the regen thumbs issue that I'm not sure you noticed.

**Comment by KFreon** [comment]
Think I've fixed this.

**Comment by ghost** [comment]
Pretty sure this isn't fixed, and is the problem being reported in Issue #310.

EDIT: Well, or it is fixed in the pre-build, but I can't test it due to the hang on hash-matching issue.

**Comment by starkgate** [comment]
@giftfish That issue applies to 748, K closed this one in one of the pre-releases for 749. I built that METPF with 748, so it is quite likely that if I were to rebuild it with 749 the issue would not be present.

**Comment by ghost** [comment]
@CreeperLava -- Yeah, that's what I mentioned in my edit above. Didn't occur to me until a half hour after I posted and re-opened, ack.

I'll re-close it, but it still needs to be tested. We can't assume it works in the pre-build, but now it's on my radar. It wasn't on my list to re-check before. Once a new pre-build is out with the hash-matching issue fixed, I'll re-check it :)

**Comment by ghost** [comment]
@CreeperLava , @KFreon -- To test this fix I took Creeper's textures from #294, and after autofixing, bundled them into a TPF. Then I loaded the TPF and analyzed. 

Here's what it looks like:

![tpfbuild_test](https://cloud.githubusercontent.com/assets/13645804/14503387/b8bd7882-0164-11e6-91e9-a77f30038d6b.PNG)

Looks like everything is found in the tree. Is the content in the Preview tab from the Texmod.log correct?

**Comment by starkgate** [comment]
Looks like it is, yes ! Do METPFs work the same ? They should, but you never know^^.

**Comment by ghost** [comment]
@CreeperLava -- METPF log looks like this:

![metpf](https://cloud.githubusercontent.com/assets/13645804/14504154/6014ef40-0168-11e6-8968-79f11095d910.PNG)

**Comment by starkgate** [comment]
Awesome, looks like this issue is fixed !

**Comment by ghost** [comment]
Wewt!

Verified in r749 prebuild v3.
